spring:
  profiles:
    active: dev
    include: mapper,business
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  application:
    name: ybg
server:
  port: 8999
  servlet:
    context-path: /ybg
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  is-print: true
  is-log: true
  token-style: uuid
  is-read-cookie: false
  is-share: false
  is-concurrent: false
  timeout: 2592000
  activity-timeout: 1800
  auto-renew: true
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 10
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 5s
